apiVersion: apps/v1
kind: Deployment
metadata:
  name: settlement-engine
  namespace: paysecure
  labels:
    app: settlement-engine
    tier: batch
spec:
  replicas: 8
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: settlement-engine
  template:
    metadata:
      labels:
        app: settlement-engine
        tier: batch
    spec:
      containers:
      - name: settlement-engine
        image: 123456789012.dkr.ecr.ap-south-1.amazonaws.com/paysecure/settlement-engine:v2.4.0
        ports:
        - containerPort: 8082
          name: http
        resources:
          requests:
            cpu: "1000m"
            memory: "2Gi"
          limits:
            cpu: "2000m"
            memory: "4Gi"
