apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: settlement-engine-hpa
  namespace: paysecure
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: settlement-engine
  minReplicas: 6
  maxReplicas: 24
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 75
